name: MirrorChyan Release Upload

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
  release:
    types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'd3ara1n' }}

    strategy:
      fail-fast: false
      matrix:
        os: [win, linux]
        arch: [x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ fromJson('{"win":"Polymerium-win-Setup.exe","linux":"Polymerium.AppImage"}')[matrix.os] }}
          mirrorchyan_rid: Polymerium
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: d3ara1n
          repo: Polymerium
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}